// <auto-generated />
using DinnerBooking.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DinnerBooking.Core.Data.Migrations
{
    [DbContext(typeof(BaseEntities))]
    [Migration("20190801070256_Add-Seed")]
    partial class AddSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DinnerBooking.Core.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<bool>("MailSent");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("DinnerBooking.Core.Data.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "是日精選"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "廚師推介"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "特價推廣"
                        });
                });

            modelBuilder.Entity("DinnerBooking.Core.Data.Entities.Cuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<int>("Count");

                    b.Property<string>("Detail");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cuisine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 5,
                            Detail = "巴西豬扒配泰式香料。",
                            Name = "泰式豬扒煲",
                            Price = 43
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 6,
                            Detail = "肉質鮮嫩，入口即溶。",
                            Name = "一口和牛",
                            Price = 35
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Count = 7,
                            Detail = "咬落爽脆，充滿蛋香。",
                            Name = "惹味煎蛋餅",
                            Price = 28
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Count = 7,
                            Detail = "和式風味，簡單精緻。",
                            Name = "日式便當",
                            Price = 33
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Count = 8,
                            Detail = "素食人士必選。",
                            Name = "純素沙律",
                            Price = 45
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Count = 9,
                            Detail = "邊辣邊爽。",
                            Name = "辣炒翠肉瓜",
                            Price = 38
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Count = 10,
                            Detail = "每日限量。",
                            Name = "出爐麵包",
                            Price = 50
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Count = 20,
                            Detail = "別有一番風味。",
                            Name = "米紙壽司卷",
                            Price = 48
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Count = 30,
                            Detail = "茶記味道，不輸老麥。",
                            Name = "港式漢堡包",
                            Price = 52
                        });
                });

            modelBuilder.Entity("DinnerBooking.Core.Data.Entities.Cuisine", b =>
                {
                    b.HasOne("DinnerBooking.Core.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
